### PR TITLE
Update to upstream 3.0.4

### PR DESCRIPTION
**Pull request by hfiguiere**
- Update runtime to 5.14
- Some minor cleanup in the manifest

### CODE REVIEW

**Comment by binaryfields** [comment]
@hfiguiere Thanks for pulling together these updates. 

I think you would also need to update PyQT5 to 5.14 as mismatched versions are probably not a good idea.

https://pypi.org/project/PyQt5/#history

**Comment by hfiguiere** [comment]
I can do it at the same time, but I don't think it matters.

**Comment by binaryfields** [comment]
I think updating would make sense. You can grab the source package from PyPI repo:

https://pypi.org/project/PyQt5/5.14.2/#files

Thanks

**Comment by hfiguiere** [comment]
Done.

**Comment by binaryfields** [comment]
This looks great. Thanks for the updates and the PR. Cheers!

**Pull request merged**
