### PR TITLE
Update to latest KDE runtime

### PR DESCRIPTION
**Pull request by FakeShemp**
This is getting 
```
Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
```
so the runtime needs to be updated.

It's currently getting a build error but couldn't find the exact culprit in the code (`cp -R ./share/locale/* /app/share/locale`) so please feel free to update the PR or leave helpful comments/patches.

### CODE REVIEW

**Comment by Midar** [comment]
Any reason this doesn't get merged? I'm now getting:

```
Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   net.fsuae.FS-UAE

Info: runtime org.freedesktop.Platform.GL.default branch 22.08-extra is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   net.fsuae.FS-UAE

Info: runtime org.freedesktop.Platform.GL.default branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   net.fsuae.FS-UAE
```

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
> Any reason this doesn't get merged? I'm now getting:

If you look at it, the build failed and it's marked as draft. For the former, ask the OP why they didn't follow up. The maintainer is AWOL.

Now it only took 3 weeks for me to post here because someone brought this to our attention on Matrix. Otherwise it would still be waiting.

So the why is simply the fact that this is run by volunteers.

**Comment by hfiguiere** [comment]
```
cp -R ./share/locale/* /app/share/locale
cp: cannot overwrite non-directory '/app/share/locale/cs' with directory './share/locale/cs'
cp: cannot overwrite non-directory '/app/share/locale/de' with directory './share/locale/de'
cp: cannot overwrite non-directory '/app/share/locale/eo' with directory './share/locale/eo'
cp: cannot overwrite non-directory '/app/share/locale/es' with directory './share/locale/es'
cp: cannot overwrite non-directory '/app/share/locale/fr' with directory './share/locale/fr'
cp: cannot overwrite non-directory '/app/share/locale/hu' with directory './share/locale/hu'
cp: cannot overwrite non-directory '/app/share/locale/it' with directory './share/locale/it'
cp: cannot overwrite non-directory '/app/share/locale/nb' with directory './share/locale/nb'
cp: cannot overwrite non-directory '/app/share/locale/nl' with directory './share/locale/nl'
cp: cannot overwrite non-directory '/app/share/locale/pl' with directory './share/locale/pl'
cp: cannot overwrite non-directory '/app/share/locale/pt' with directory './share/locale/pt'
cp: cannot overwrite non-directory '/app/share/locale/sr' with directory './share/locale/sr'
cp: cannot overwrite non-directory '/app/share/locale/sv' with directory './share/locale/sv'
cp: cannot overwrite non-directory '/app/share/locale/tr' with directory './share/locale/tr'
make[4]: *** [Makefile:5050: install-data-hook] Error 1
make[4]: Leaving directory '/run/build/fs-uae-jit'
make[3]: *** [Makefile:4829: install-data-am] Error 2
make[3]: Leaving directory '/run/build/fs-uae-jit'
make[2]: *** [Makefile:4708: install-am] Error 2
make[2]: Leaving directory '/run/build/fs-uae-jit'
make[1]: *** [Makefile:4241: install-recursive] Error 1
make[1]: Leaving directory '/run/build/fs-uae-jit'
make: *** [Makefile:4702: install] Error 2
FB: host_command_exited_cb 2346864 512
]2;flatpak-builder: Cleanup fs-uae-jitError: module fs-uae-jit: Child process exited with code 2
```

**Pull request closed without merging**
