### PR TITLE
Update runtime to 22.08

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by binaryfields** [comment]
FS-UAE Launcher fails with some missing dependencies.

After installing the build locally, try running the following:

> /usr/bin/flatpak run --user --branch=stable --arch=x86_64 --command=fs-uae-launcher --file-forwarding net.fsuae.FS-UAE

**Comment by hfiguiere** [comment]
lines 44 and 47 need changes too, thanks to Python 3.10

**Comment by hfiguiere** [comment]
FYI the error message:
```
['/app/bin/fs-uae-launcher']
uname_result(system='Linux', node='rocinante', release='5.18.13-200.fc36.x86_64', version='#1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022', machine='x86_64')

Unhandled exception detected in thread MainThread:
  ModuleNotFoundError:qt.py:<module>:12

Traceback (most recent call last):
  File "/app/bin/fs-uae-launcher", line 121, in <module>
    main()
  File "/app/bin/fs-uae-launcher", line 118, in main
    launcher.apps.main()
  File "/app/share/fs-uae-launcher/launcher/apps/__init__.py", line 137, in main
    app_main()
  File "/app/share/fs-uae-launcher/launcher/apps/fs_uae_launcher.py", line 22, in app_main
    from launcher.launcherapp import LauncherApp
  File "/app/share/fs-uae-launcher/launcher/launcherapp.py", line 9, in <module>
    import fsui
  File "/app/share/fs-uae-launcher/fsui/__init__.py", line 5, in <module>
    from fsui.qt import *
  File "/app/share/fs-uae-launcher/fsui/qt/__init__.py", line 5, in <module>
    from fsui.qt.qt import (
  File "/app/share/fs-uae-launcher/fsui/qt/qt.py", line 12, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.QtCore'


Unhandled exception detected in thread MainThread:
  ModuleNotFoundError:qt.py:<module>:12

Traceback (most recent call last):
  File "/app/bin/fs-uae-launcher", line 121, in <module>
    main()
  File "/app/bin/fs-uae-launcher", line 118, in main
    launcher.apps.main()
  File "/app/share/fs-uae-launcher/launcher/apps/__init__.py", line 137, in main
    app_main()
  File "/app/share/fs-uae-launcher/launcher/apps/fs_uae_launcher.py", line 22, in app_main
    from launcher.launcherapp import LauncherApp
  File "/app/share/fs-uae-launcher/launcher/launcherapp.py", line 9, in <module>
    import fsui
  File "/app/share/fs-uae-launcher/fsui/__init__.py", line 5, in <module>
    from fsui.qt import *
  File "/app/share/fs-uae-launcher/fsui/qt/__init__.py", line 5, in <module>
    from fsui.qt.qt import (
  File "/app/share/fs-uae-launcher/fsui/qt/qt.py", line 12, in <module>
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.QtCore'
```

**Comment by hfiguiere** [comment]
also a note that fs-uae-launcher isn't the default command either.
Simpler launch command:
```
 flatpak run --command=fs-uae-launcher net.fsuae.FS-UAE
```

**Comment by FakeShemp** [comment]
bot, build

**Comment by binaryfields** [comment]
Thanks for the PR. Launcher worked great with these changes.

**Pull request merged**
